### ISSUE TITLE
On Android 10, the IPv6 of WiFi cannot be turned off after the module is swiped in, and IPv6 test can still pass

### ISSUE THREAD

**Issue by HorrZzz** [njallam/magisk-disable-ipv6#1]
On Android 10, the IPv6 of WiFi cannot be turned off after the module is swiped in, and IPv6 test can still pass。
This sentence does not take effect------echo 0 > /proc/sys/net/ipv6/conf/wlan0/accept_ra

**Comment by crackevil** [comment]
the "echo" way does not work really, use "sysctl" instead
